export const projects = [
  {
    id: 1,
    name: "aura",
    title: "Kaunas Zoo",
    subtitle: "Šokio spektaklis",
    description:
      "Imprvizacinės muzikos grupės Kaunas Zoo ir Auros šokio teatro sukurtas pasirodymas pelnęs 'Fortūnos diplomą' už muziką.",
    roles: ["composer", "coordinator", "arranger"],
  },
  {
    id: 2,
    name: "biciulyste",
    title: "Bičiulystė",
    subtitle: "Interaktyvi skulptūra",
    description: "",
    roles: ["composer", "coordinator", "arranger"],
  },
  {
    id: 3,
    name: "cosmic_mass",
    title: "Cosmic Mass",
    subtitle: "Interaktyvi skulptūra",
    description: "",
    roles: ["composer", "coordinator", "arranger"],
  },
  {
    id: 4,
    name: "eels",
    title: "Skaitymai",
    subtitle: "Interaktyvi skulptūra",
    description: "",
    roles: ["composer", "coordinator", "arranger"],
  },
  {
    id: 5,
    name: "left_choir",
    title: "Kairiųjų Choras",
    subtitle: "Interaktyvi skulptūra",
    description: "",
    roles: ["composer", "coordinator", "arranger"],
  },
  {
    id: 6,
    name: "refugees",
    title: "Stovykla",
    subtitle: "Interaktyvi skulptūra",
    description: "",
    roles: ["composer", "coordinator", "arranger"],
  },
  {
    id: 7,
    name: "sauna",
    title: "Audio Pirtis",
    subtitle: "Interaktyvi skulptūra",
    description: "",
    roles: ["composer", "coordinator", "arranger"],
  },
  {
    id: 8,
    name: "theater",
    title: "Teatro Dirbtuvės",
    subtitle: "Interaktyvi skulptūra",
    description: "",
    roles: ["composer", "coordinator", "arranger"],
  },
  {
    id: 9,
    name: "vmd",
    title: "Vaikų Muzikos Diena",
    subtitle: "Interaktyvi skulptūra",
    description: "",
    roles: ["composer", "coordinator", "arranger"],
  },
];

const roleCategories = {
  composer: "music",
  coordinator: "admin",
  arranger: "music",
  animator: "visual",
  designer: "visual",
  programming: "tech",
  website: "tech",
};
